### ISSUE TITLE
Demo启动即报错 java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Jucyfer** [nicai0609/JAVA-CTPAPI#7]
Exception in thread "main" java.lang.NoSuchMethodError: SwigDirector_CThostFtdcMdSpi_OnRspQryMulticastInstrument
	at ctp.thostapi.thosttraderapiJNI.swig_module_init(Native Method)
	at ctp.thostapi.thosttraderapiJNI.<clinit>(thosttraderapiJNI.java:10453)
	at ctp.thostapi.CThostFtdcTraderApi.CreateFtdcTraderApi(CThostFtdcTraderApi.java:35)
	at ctpapi.ctpdemo.main(ctpdemo.java:214)

**Comment by xzyterry** [comment]
俺也一样

**Comment by mfkvfn** [comment]
应该是 dll版本与它这个不兼容导致的。
如果用不上这个方法，可以从反反编译一份java代码，然后从java源代码中删除这个方法，然后重新编译到jar。
